"""empty message

Revision ID: 00ba2ef7f297
Revises: 1bc3c67436a5
Create Date: 2020-03-12 00:08:34.639313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ba2ef7f297'
down_revision = '1bc3c67436a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streaming', sa.Column('server', sa.String(length=128), nullable=True))
    op.add_column('streaming', sa.Column('stream_key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streaming', 'stream_key')
    op.drop_column('streaming', 'server')
    # ### end Alembic commands ###
