"""readd streaming table

Revision ID: 1bc3c67436a5
Revises: 2b7af978dcd6
Create Date: 2020-03-06 15:24:25.513478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc3c67436a5'
down_revision = '2b7af978dcd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaming',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaming_timestamp'), 'streaming', ['timestamp'], unique=False)
    op.create_index(op.f('ix_streaming_title'), 'streaming', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaming_title'), table_name='streaming')
    op.drop_index(op.f('ix_streaming_timestamp'), table_name='streaming')
    op.drop_table('streaming')
    # ### end Alembic commands ###
