"""borrar tabla streaming

Revision ID: 2b7af978dcd6
Revises: 3fab54bc994e
Create Date: 2020-03-06 15:22:31.215574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7af978dcd6'
down_revision = '3fab54bc994e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_streaming_timestamp', table_name='streaming')
    op.drop_index('ix_streaming_title', table_name='streaming')
    op.drop_table('streaming')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaming',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('complete', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('complete IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_streaming_title', 'streaming', ['title'], unique=False)
    op.create_index('ix_streaming_timestamp', 'streaming', ['timestamp'], unique=False)
    # ### end Alembic commands ###
