"""fixing primary key streaming, adding timestamp

Revision ID: 3fab54bc994e
Revises: 34a98d26da39
Create Date: 2020-03-06 15:17:52.020101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fab54bc994e'
down_revision = '34a98d26da39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streaming', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_streaming_timestamp'), 'streaming', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaming_timestamp'), table_name='streaming')
    op.drop_column('streaming', 'timestamp')
    # ### end Alembic commands ###
