"""empty message

Revision ID: f41c17a8d96b
Revises: 01997d8d518c
Create Date: 2020-03-16 01:03:33.926195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41c17a8d96b'
down_revision = '01997d8d518c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streaming', sa.Column('job_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streaming', 'job_id')
    # ### end Alembic commands ###
